# Generated by Django 4.2.11 on 2024-04-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionProduccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_adquisicion', models.DateField()),
                ('fecha_instalacion', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='orden_De_fabricacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_fabricacion', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orden de fabricacion',
                'verbose_name_plural': 'Ordenes de fabricacion',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_orden_fabricacion', models.CharField(max_length=10)),
                ('codigo_proceso', models.CharField(max_length=10, unique=True)),
                ('nombre_proceso', models.CharField(max_length=50)),
                ('referencia', models.CharField(max_length=50)),
                ('equipo', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('empleado_asignados', models.ManyToManyField(to='appGestionProduccion.empleado')),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
                'ordering': ['-created'],
            },
        ),
    ]
