# Generated by Django 4.2.11 on 2024-04-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionProduccion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proceso',
            old_name='empleado_asignados',
            new_name='empleados_asignados',
        ),
    ]
