# Generated by Django 4.2.11 on 2024-04-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionProduccion', '0002_rename_empleado_asignados_proceso_empleados_asignados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceso',
            name='referencia_de_fabricacion',
        ),
        migrations.AddField(
            model_name='proceso',
            name='referencia_de_fabricacion',
            field=models.ManyToManyField(to='appGestionProduccion.orden_de_fabricacion'),
        ),
    ]
