# Generated by Django 4.2.11 on 2024-05-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionProduccion', '0003_remove_proceso_referencia_de_fabricacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='procesos/'),
        ),
    ]
