# Generated by Django 4.2.11 on 2024-05-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionProduccion', '0004_proceso_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='equipo/'),
        ),
    ]
